apiVersion: apps/v1
kind: Deployment
metadata:
  name: appservice
spec:
  selector:
    matchLabels:
      app: appservice
  template:
    metadata:
      labels:
        app: appservice
    spec:
      containers:
        - name: web
          image: nginx:latest
        - name: appservice
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              value: "root"
            - name: "MYSQL_DATABASE"
              value: "minsait"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          hostPath:
            path: /mysql
---
apiVersion: v1
kind: Service
metadata:
  name: appservice
spec:
  selector:
    app: appservice
  ports:
    - port: 3306
  type: ClusterIP
